import "server-only";
import { createCipheriv, createDecipheriv, createHash, createHmac, randomBytes, timingSafeEqual } from "node:crypto";
import bcrypt from "bcryptjs";
import { prisma } from "@/lib/prisma";

const BASE32 = "ABCDEFGHIJKLMNOPQRSTUVWXYZ234567";
const CODE_WINDOW_MS = 30_000;

function encryptionKey(): Buffer | null {
  // A 40+ character value generated by a password manager is simple to put
  // into Vercel, and SHA-256 deterministically turns it into the AES-256 key.
  // The original value never enters the database or the browser.
  const value = process.env.MFA_ENCRYPTION_KEY?.trim();
  if (!value || value.length < 32) return null;
  return createHash("sha256").update(value, "utf8").digest();
}

function encrypt(value: string): string | null {
  const key = encryptionKey();
  if (!key) return null;
  const iv = randomBytes(12);
  const cipher = createCipheriv("aes-256-gcm", key, iv);
  const ciphertext = Buffer.concat([cipher.update(value, "utf8"), cipher.final()]);
  return [iv, cipher.getAuthTag(), ciphertext].map((part) => part.toString("base64url")).join(".");
}

function decrypt(value: string): string | null {
  const key = encryptionKey();
  const parts = value.split(".");
  if (!key || parts.length !== 3) return null;
  try {
    const [iv, tag, ciphertext] = parts.map((part) => Buffer.from(part, "base64url"));
    const decipher = createDecipheriv("aes-256-gcm", key, iv);
    decipher.setAuthTag(tag);
    return Buffer.concat([decipher.update(ciphertext), decipher.final()]).toString("utf8");
  } catch { return null; }
}

function randomBase32(bytes = 20): string {
  const source = randomBytes(bytes);
  let bits = 0; let value = 0; let output = "";
  for (const byte of source) {
    value = (value << 8) | byte; bits += 8;
    while (bits >= 5) { output += BASE32[(value >>> (bits - 5)) & 31]; bits -= 5; }
  }
  return output;
}

function decodeBase32(value: string): Buffer | null {
  let bits = 0; let buffer = 0; const output: number[] = [];
  for (const character of value.replace(/[\s=-]/g, "").toUpperCase()) {
    const index = BASE32.indexOf(character);
    if (index < 0) return null;
    buffer = (buffer << 5) | index; bits += 5;
    if (bits >= 8) { output.push((buffer >>> (bits - 8)) & 255); bits -= 8; }
  }
  return Buffer.from(output);
}

function totp(secret: string, timestamp = Date.now()): string | null {
  const bytes = decodeBase32(secret);
  if (!bytes) return null;
  const counter = Math.floor(timestamp / CODE_WINDOW_MS);
  const counterBytes = Buffer.alloc(8); counterBytes.writeBigUInt64BE(BigInt(counter));
  const digest = createHmac("sha1", bytes).update(counterBytes).digest();
  const offset = digest[digest.length - 1] & 15;
  const number = ((digest[offset] & 127) << 24) | (digest[offset + 1] << 16) | (digest[offset + 2] << 8) | digest[offset + 3];
  return String(number % 1_000_000).padStart(6, "0");
}

function validCode(secret: string, supplied: string): boolean {
  const code = supplied.replace(/\s/g, "");
  if (!/^\d{6}$/.test(code)) return false;
  return [-1, 0, 1].some((offset) => {
    const expected = totp(secret, Date.now() + offset * CODE_WINDOW_MS);
    return expected !== null && timingSafeEqual(Buffer.from(expected), Buffer.from(code));
  });
}

function isStaff(roleKeys: readonly string[]): boolean {
  return roleKeys.some((key) => !["PATIENT", "AUTHORIZED_FAMILY", "REFERRAL_PARTNER"].includes(key));
}

function recoveryHash(code: string): string { return createHash("sha256").update(code).digest("hex"); }
function recoveryCodes(): string[] {
  // 64 random bits per code. Codes are displayed exactly once; only their
  // SHA-256 hashes are retained, so a database export cannot be used to log in.
  return Array.from({ length: 10 }, () => randomBytes(8).toString("hex").match(/.{1,4}/g)?.join("-").toUpperCase() ?? "");
}

export async function hasActiveMfa(userId: string): Promise<boolean> {
  return (await prisma.mfaFactor.findUnique({ where: { userId }, select: { status: true } }))?.status === "active";
}

export async function getMfaStatus(userId: string): Promise<"off" | "pending" | "active"> {
  const factor = await prisma.mfaFactor.findUnique({ where: { userId }, select: { status: true } });
  return factor?.status === "active" ? "active" : factor?.status === "pending" ? "pending" : "off";
}

export type EnrollmentStart = { ok: true; manualKey: string } | { ok: false; error: string };

export async function beginMfaEnrollment(userId: string, password: string, roleKeys: readonly string[]): Promise<EnrollmentStart> {
  if (!isStaff(roleKeys)) return { ok: false, error: "MFA is available for staff accounts only." };
  const user = await prisma.user.findUnique({ where: { id: userId }, select: { passwordHash: true } });
  if (!user || !(await bcrypt.compare(password, user.passwordHash))) return { ok: false, error: "Password confirmation did not match." };
  const secret = randomBase32(); const encryptedSecret = encrypt(secret);
  if (!encryptedSecret) return { ok: false, error: "MFA setup is not configured yet." };
  await prisma.mfaFactor.upsert({ where: { userId }, update: { encryptedSecret, status: "pending", recoveryCodeHashes: [], verifiedAt: null }, create: { userId, encryptedSecret, recoveryCodeHashes: [] } });
  return { ok: true, manualKey: secret };
}

export type EnrollmentConfirm = { ok: true; recoveryCodes: string[] } | { ok: false; error: string };

export async function confirmMfaEnrollment(userId: string, code: string): Promise<EnrollmentConfirm> {
  const factor = await prisma.mfaFactor.findUnique({ where: { userId }, select: { status: true, encryptedSecret: true } });
  const secret = factor && factor.status === "pending" ? decrypt(factor.encryptedSecret) : null;
  if (!secret || !validCode(secret, code)) return { ok: false, error: "That authenticator code did not match. Try the newest code." };
  const codes = recoveryCodes();
  await prisma.mfaFactor.update({ where: { userId }, data: { status: "active", recoveryCodeHashes: codes.map(recoveryHash), verifiedAt: new Date(), lastUsedAt: new Date() } });
  return { ok: true, recoveryCodes: codes };
}

export async function verifyMfa(userId: string, code: string): Promise<{ ok: boolean; usedRecoveryCode: boolean }> {
  const factor = await prisma.mfaFactor.findUnique({ where: { userId }, select: { status: true, encryptedSecret: true, recoveryCodeHashes: true } });
  if (!factor || factor.status !== "active") return { ok: false, usedRecoveryCode: false };
  const secret = decrypt(factor.encryptedSecret);
  if (secret && validCode(secret, code)) { await prisma.mfaFactor.update({ where: { userId }, data: { lastUsedAt: new Date() } }); return { ok: true, usedRecoveryCode: false }; }
  const hash = recoveryHash(code.trim().toUpperCase());
  if (!factor.recoveryCodeHashes.includes(hash)) return { ok: false, usedRecoveryCode: false };
  await prisma.mfaFactor.update({ where: { userId }, data: { recoveryCodeHashes: factor.recoveryCodeHashes.filter((stored) => stored !== hash), lastUsedAt: new Date() } });
  return { ok: true, usedRecoveryCode: true };
}
